config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :doctors
  resources :patients do
    resources :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  accepts_nested_attributes_for :patient, reject_if: :all_blank

  # def patient_attributes=(patient_attributes)
  #   patient = Patient.create(patient_attributes)
  #   self.patient = patient
  #   self.save
  # end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments 
  has_many :patients, through: :appointments
  has_secure_password 
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
  validates :name, presence: true
  def hello
    puts greeting
  end

  private

  def greeting
    'Hello World'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_doctor
    @doctor ||= Doctor.first
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find_by_id(params[:id])
  end

  def new
    @patient = Patient.find_by_id(params[:patient_id]) if params[:patient_id]
    @appointment = Appointment.new
  end

  def create
    @appointment = current_doctor.appointments.create(appointment_params)
    redirect_to appointment_path(@appointment)
  end

  def edit
    set_appointment
  end

  def update
    set_appointment
    @appointment.update(appointment_params)
    redirect_to appointment_path(@appointment)
  end

  def destroy
    set_appointment
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def set_appointment
    @appointment = Appointment.find_by_id(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:patient_id, :date, :time, :notes, patient_attributes: %i[name age bmi phone_number])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find_by_id(params[:id])
  end

  def new 
    @patient = Patient.new
  end

  def create 
    @patient = Patient.create(patient_params)
    redirect_to patient_path(@patient)
  end

  def edit 
    set_patient
  end 

  def update 
    set_patient
    @patient.update(patient_params)
    redirect_to patient_path(@patient)
  end

  def destroy 
    set_patient
    @patient.destroy 
    redirect_to patients_path
  end

  
  private 

  def set_patient 
    @patient = Patient.find_by_id(params[:id])
  end

  def patient_params 
    params.require(:patient).permit(:name, :age, :bmi, :phone_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<%= form_for @appointment do |f| %>
  <%if @patient%>
    <h3>New Appointment for: <%=@patient.name%></h3>
    <%=f.hidden_field :patient_id, value:@patient.id%>
  <%else%>
    <h3>Select Existing Patient:</h3>
    <%= f.select :patient_id, Patient.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
    <h3>Or, Create a New Patient:</h3>
    <%=f.fields_for :patient, Patient.new do |patient_fields| %>
      <p><%= patient_fields.label "Name" %></p>
      <p><%= patient_fields.text_field :name %></p>
      <p><%= patient_fields.label "Age" %></p>
      <p><%= patient_fields.text_field :age %></p>
      <p><%= patient_fields.label "Body Mass Index" %></p>
      <p><%= patient_fields.text_field :bmi %></p>
      <p><%= patient_fields.label "Phone Number" %></p>
      <p><%= patient_fields.text_field :phone_number %></p>
    <%end%>
  <%end%>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.label :time %>
  <%= f.time_field :time %>
  <%= f.submit %>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointment details for: <%=@appointment.patient.name%></h1>
<ul>
  <li>Doctor: <%=@appointment.doctor.username%></li>
  <li>Date: <%=@appointment.date%></li>
  <li>Time: <%=@appointment.time%></li>
  <li>Notes: <%=@appointment.notes%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pod4Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Edit Current Patients</h1>
<p><%= form_for @patient do |f| %></p>
  <p><%= f.label "Name" %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label "Age" %></p>
  <p><%= f.text_field :age %></p>
  <p><%= f.label "Body Mass Index" %></p>
  <p><%= f.text_field :bmi %></p>
  <p><%= f.label "Phone Number" %></p>
  <p><%= f.text_field :phone_number %></p>
  <p><%= f.submit "Update Patient" %></p>
  <% end %>

app/views/patients/index.html.erb
<h1>All Patients</h1>
<h3><div><%= link_to "New Patient Form", new_patient_path %></div></h3>

<% @patients.each do |patient| %>
  <h2><p><%=link_to patient.name, patient_path(patient)%></p></h2>
  <%= link_to "Edit", edit_patient_path(patient) %>
  <%= link_to "Delete Patient", patient, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
 

app/views/patients/new.html.erb
<h1>New Patients</h1>
<p><%= form_for @patient do |f| %></p>
  <p><%= f.label "Name" %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label "Age" %></p>
  <p><%= f.text_field :age %></p>
  <p><%= f.label "Body Mass Index" %></p>
  <p><%= f.text_field :bmi %></p>
  <p><%= f.label "Phone Number" %></p>
  <p><%= f.text_field :phone_number %></p>
  <p><%= f.submit "Create New Patient" %></p>
  <% end %>

app/views/patients/show.html.erb
<h1><%=@patient.name%></h1>
<h3>Vitals:</h3>
<p>BMI: <%=@patient.bmi%></p>
<p>Age: <%=@patient.age%></p>
<h3>Contact Info:</h3>
<p>Phone: <%=@patient.phone_number%></p>
<%=link_to "Create Appointment", new_patient_appointment_path(@patient)%>
<%= link_to 'Back',  patients_path%>